=== itzTerra/PLC/data/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="syntax" type="xs:anyType"/>
        <xs:element name="comments" type="xs:anyType"/>
        <xs:element name="output" type="xs:anyType"/>
        <xs:element name="datatypes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="general" type="xs:anyType"/>
              <xs:element name="boolean" type="xs:anyType"/>
              <xs:element name="numeric" type="xs:anyType"/>
              <xs:element name="string" type="xs:anyType"/>
              <xs:element name="array" type="xs:anyType"/>
              <xs:element name="hashtable" type="xs:anyType"/>
              <xs:element name="other" type="xs:anyType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="operators">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="arithmetic" type="xs:anyType"/>
              <xs:element name="logrel" type="xs:anyType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="loops">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="for" type="xs:anyType"/>
              <xs:element name="while" type="xs:anyType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="OOP">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="overview" type="xs:anyType"/>
              <xs:element name="example" type="xs:anyType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== itzTerra/PLC/data/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
    <syntax></syntax>
    <variables></variables>
    <comments></comments>
    <output></output>
    <datatypes>
        <general></general>
        <boolean></boolean>
        <numeric></numeric>
        <string></string>
        <array></array>
        <hashtable></hashtable>
        <other></other>
    </datatypes>
    <operators>
        <arithmetic></arithmetic>
        <logrel></logrel>
    </operators>
    <loops>
        <for></for>
        <while></while>
    </loops>
    <OOP>
        <overview></overview>
        <example></example>
    </OOP>
</root>
